module Evergreen.Migrate.V2 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V1.Crate
import Evergreen.V1.Gamepad
import Evergreen.V1.Gamepad.Advanced
import Evergreen.V1.Gamepad.Private
import Evergreen.V1.Types
import Evergreen.V2.Crate
import Evergreen.V2.Gamepad
import Evergreen.V2.Gamepad.Advanced
import Evergreen.V2.Gamepad.Private
import Evergreen.V2.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V1.Types.FrontendModel -> ModelMigration Evergreen.V2.Types.FrontendModel Evergreen.V2.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V1.Types.BackendModel -> ModelMigration Evergreen.V2.Types.BackendModel Evergreen.V2.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V1.Types.FrontendMsg -> MsgMigration Evergreen.V2.Types.FrontendMsg Evergreen.V2.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V1.Types.ToBackend -> MsgMigration Evergreen.V2.Types.ToBackend Evergreen.V2.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V1.Types.BackendMsg -> MsgMigration Evergreen.V2.Types.BackendMsg Evergreen.V2.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V1.Types.ToFrontend -> MsgMigration Evergreen.V2.Types.ToFrontend Evergreen.V2.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V1.Types.FrontendModel -> Evergreen.V2.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , crate = old.crate |> migrate_Crate_Model
    , gamepadState = old.gamepadState |> migrate_Types_GamepadState
    , userMappings = old.userMappings |> migrate_Gamepad_Advanced_UserMappings
    }


migrate_Crate_Model : Evergreen.V1.Crate.Model -> Evergreen.V2.Crate.Model
migrate_Crate_Model old =
    old


migrate_Crate_Msg : Evergreen.V1.Crate.Msg -> Evergreen.V2.Crate.Msg
migrate_Crate_Msg old =
    case old of
        Evergreen.V1.Crate.TextureLoaded p0 ->
            Evergreen.V2.Crate.TextureLoaded p0

        Evergreen.V1.Crate.Animate p0 ->
            Evergreen.V2.Crate.Animate p0


migrate_Gamepad_Advanced_Blob : Evergreen.V1.Gamepad.Advanced.Blob -> Evergreen.V2.Gamepad.Advanced.Blob
migrate_Gamepad_Advanced_Blob old =
    old |> migrate_Gamepad_Private_Blob


migrate_Gamepad_Advanced_Model : Evergreen.V1.Gamepad.Advanced.Model -> Evergreen.V2.Gamepad.Advanced.Model
migrate_Gamepad_Advanced_Model old =
    case old of
        Evergreen.V1.Gamepad.Advanced.Model p0 ->
            Evergreen.V2.Gamepad.Advanced.Model (p0 |> migrate_Gamepad_Advanced_WrappedModel)


migrate_Gamepad_Advanced_Msg : Evergreen.V1.Gamepad.Advanced.Msg -> Evergreen.V2.Gamepad.Advanced.Msg
migrate_Gamepad_Advanced_Msg old =
    case old of
        Evergreen.V1.Gamepad.Advanced.Noop ->
            Evergreen.V2.Gamepad.Advanced.Noop

        Evergreen.V1.Gamepad.Advanced.OnGamepad p0 ->
            Evergreen.V2.Gamepad.Advanced.OnGamepad (p0 |> migrate_Gamepad_Advanced_Blob)

        Evergreen.V1.Gamepad.Advanced.OnStartRemapping p0 p1 ->
            Evergreen.V2.Gamepad.Advanced.OnStartRemapping p0 p1

        Evergreen.V1.Gamepad.Advanced.OnSkip p0 ->
            Evergreen.V2.Gamepad.Advanced.OnSkip (p0 |> migrate_Gamepad_Digital)

        Evergreen.V1.Gamepad.Advanced.OnCancel ->
            Evergreen.V2.Gamepad.Advanced.OnCancel


migrate_Gamepad_Advanced_Remapping : Evergreen.V1.Gamepad.Advanced.Remapping -> Evergreen.V2.Gamepad.Advanced.Remapping
migrate_Gamepad_Advanced_Remapping old =
    { id = old.id
    , index = old.index
    , pairs = old.pairs |> List.map (Tuple.mapBoth migrate_Gamepad_Private_Origin migrate_Gamepad_Digital)
    , skipped = old.skipped |> List.map migrate_Gamepad_Digital
    , waitingFor = old.waitingFor |> migrate_Gamepad_Advanced_WaitingFor
    }


migrate_Gamepad_Advanced_UserMappings : Evergreen.V1.Gamepad.Advanced.UserMappings -> Evergreen.V2.Gamepad.Advanced.UserMappings
migrate_Gamepad_Advanced_UserMappings old =
    case old of
        Evergreen.V1.Gamepad.Advanced.UserMappings p0 ->
            Evergreen.V2.Gamepad.Advanced.UserMappings
                { byIndexAndId = p0.byIndexAndId |> Dict.map (\k -> migrate_Gamepad_Private_Mapping)
                , byId = p0.byId |> Dict.map (\k -> migrate_Gamepad_Private_Mapping)
                }


migrate_Gamepad_Advanced_WaitingFor : Evergreen.V1.Gamepad.Advanced.WaitingFor -> Evergreen.V2.Gamepad.Advanced.WaitingFor
migrate_Gamepad_Advanced_WaitingFor old =
    case old of
        Evergreen.V1.Gamepad.Advanced.AllButtonsUp ->
            Evergreen.V2.Gamepad.Advanced.AllButtonsUp

        Evergreen.V1.Gamepad.Advanced.SomeButtonDown ->
            Evergreen.V2.Gamepad.Advanced.SomeButtonDown


migrate_Gamepad_Advanced_WrappedModel : Evergreen.V1.Gamepad.Advanced.WrappedModel -> Evergreen.V2.Gamepad.Advanced.WrappedModel
migrate_Gamepad_Advanced_WrappedModel old =
    { blob = old.blob |> migrate_Gamepad_Advanced_Blob
    , maybeRemapping = old.maybeRemapping |> Maybe.map migrate_Gamepad_Advanced_Remapping
    , controls = old.controls |> List.map (Tuple.mapSecond migrate_Gamepad_Digital)
    }


migrate_Gamepad_Digital : Evergreen.V1.Gamepad.Digital -> Evergreen.V2.Gamepad.Digital
migrate_Gamepad_Digital old =
    case old of
        Evergreen.V1.Gamepad.A ->
            Evergreen.V2.Gamepad.A

        Evergreen.V1.Gamepad.B ->
            Evergreen.V2.Gamepad.B

        Evergreen.V1.Gamepad.X ->
            Evergreen.V2.Gamepad.X

        Evergreen.V1.Gamepad.Y ->
            Evergreen.V2.Gamepad.Y

        Evergreen.V1.Gamepad.Start ->
            Evergreen.V2.Gamepad.Start

        Evergreen.V1.Gamepad.Back ->
            Evergreen.V2.Gamepad.Back

        Evergreen.V1.Gamepad.Home ->
            Evergreen.V2.Gamepad.Home

        Evergreen.V1.Gamepad.LeftStickPress ->
            Evergreen.V2.Gamepad.LeftStickPress

        Evergreen.V1.Gamepad.LeftStickUp ->
            Evergreen.V2.Gamepad.LeftStickUp

        Evergreen.V1.Gamepad.LeftStickDown ->
            Evergreen.V2.Gamepad.LeftStickDown

        Evergreen.V1.Gamepad.LeftStickLeft ->
            Evergreen.V2.Gamepad.LeftStickLeft

        Evergreen.V1.Gamepad.LeftStickRight ->
            Evergreen.V2.Gamepad.LeftStickRight

        Evergreen.V1.Gamepad.LeftTrigger ->
            Evergreen.V2.Gamepad.LeftTrigger

        Evergreen.V1.Gamepad.LeftBumper ->
            Evergreen.V2.Gamepad.LeftBumper

        Evergreen.V1.Gamepad.RightStickPress ->
            Evergreen.V2.Gamepad.RightStickPress

        Evergreen.V1.Gamepad.RightStickUp ->
            Evergreen.V2.Gamepad.RightStickUp

        Evergreen.V1.Gamepad.RightStickDown ->
            Evergreen.V2.Gamepad.RightStickDown

        Evergreen.V1.Gamepad.RightStickLeft ->
            Evergreen.V2.Gamepad.RightStickLeft

        Evergreen.V1.Gamepad.RightStickRight ->
            Evergreen.V2.Gamepad.RightStickRight

        Evergreen.V1.Gamepad.RightTrigger ->
            Evergreen.V2.Gamepad.RightTrigger

        Evergreen.V1.Gamepad.RightBumper ->
            Evergreen.V2.Gamepad.RightBumper

        Evergreen.V1.Gamepad.DpadUp ->
            Evergreen.V2.Gamepad.DpadUp

        Evergreen.V1.Gamepad.DpadDown ->
            Evergreen.V2.Gamepad.DpadDown

        Evergreen.V1.Gamepad.DpadLeft ->
            Evergreen.V2.Gamepad.DpadLeft

        Evergreen.V1.Gamepad.DpadRight ->
            Evergreen.V2.Gamepad.DpadRight


migrate_Gamepad_Private_Blob : Evergreen.V1.Gamepad.Private.Blob -> Evergreen.V2.Gamepad.Private.Blob
migrate_Gamepad_Private_Blob old =
    old |> (\( t1, t2, t3 ) -> ( t1 |> migrate_Gamepad_Private_BlobFrame, t2 |> migrate_Gamepad_Private_BlobFrame, t3 |> migrate_Gamepad_Private_Environment ))


migrate_Gamepad_Private_BlobFrame : Evergreen.V1.Gamepad.Private.BlobFrame -> Evergreen.V2.Gamepad.Private.BlobFrame
migrate_Gamepad_Private_BlobFrame old =
    old


migrate_Gamepad_Private_Environment : Evergreen.V1.Gamepad.Private.Environment -> Evergreen.V2.Gamepad.Private.Environment
migrate_Gamepad_Private_Environment old =
    old


migrate_Gamepad_Private_Mapping : Evergreen.V1.Gamepad.Private.Mapping -> Evergreen.V2.Gamepad.Private.Mapping
migrate_Gamepad_Private_Mapping old =
    old |> Dict.map (\k -> migrate_Gamepad_Private_Origin)


migrate_Gamepad_Private_Origin : Evergreen.V1.Gamepad.Private.Origin -> Evergreen.V2.Gamepad.Private.Origin
migrate_Gamepad_Private_Origin old =
    case old of
        Evergreen.V1.Gamepad.Private.Origin p0 p1 p2 ->
            Evergreen.V2.Gamepad.Private.Origin p0 (p1 |> migrate_Gamepad_Private_OriginType) p2


migrate_Gamepad_Private_OriginType : Evergreen.V1.Gamepad.Private.OriginType -> Evergreen.V2.Gamepad.Private.OriginType
migrate_Gamepad_Private_OriginType old =
    case old of
        Evergreen.V1.Gamepad.Private.Axis ->
            Evergreen.V2.Gamepad.Private.Axis

        Evergreen.V1.Gamepad.Private.Button ->
            Evergreen.V2.Gamepad.Private.Button


migrate_Types_FrontendMsg : Evergreen.V1.Types.FrontendMsg -> Evergreen.V2.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V1.Types.UrlClicked p0 ->
            Evergreen.V2.Types.UrlClicked p0

        Evergreen.V1.Types.UrlChanged p0 ->
            Evergreen.V2.Types.UrlChanged p0

        Evergreen.V1.Types.CrateMsg p0 ->
            Evergreen.V2.Types.CrateMsg (p0 |> migrate_Crate_Msg)

        Evergreen.V1.Types.OnAnimationFrame p0 ->
            Evergreen.V2.Types.OnAnimationFrame (p0 |> migrate_Gamepad_Advanced_Blob)

        Evergreen.V1.Types.OnRemappingToolMsg p0 ->
            Evergreen.V2.Types.OnRemappingToolMsg (p0 |> migrate_Gamepad_Advanced_Msg)

        Evergreen.V1.Types.OnToggleRemap ->
            Evergreen.V2.Types.OnToggleRemap

        Evergreen.V1.Types.NoOpFrontendMsg ->
            Evergreen.V2.Types.NoOpFrontendMsg


migrate_Types_GamepadState : Evergreen.V1.Types.GamepadState -> Evergreen.V2.Types.GamepadState
migrate_Types_GamepadState old =
    case old of
        Evergreen.V1.Types.Initializing ->
            Evergreen.V2.Types.Initializing

        Evergreen.V1.Types.DisplayingGamepads p0 ->
            Evergreen.V2.Types.DisplayingGamepads (p0 |> migrate_Gamepad_Advanced_Blob)

        Evergreen.V1.Types.RemappingTool p0 ->
            Evergreen.V2.Types.RemappingTool (p0 |> migrate_Gamepad_Advanced_Model)
